//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v2.0.50727.5466
//


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WareHouseSoap", Namespace="http://tempuri.org/")]
public partial class WareHouse : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback ReturnItemOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateMoneyUserOperationCompleted;
    
    private System.Threading.SendOrPostCallback BuyItemOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetMedalOperationCompleted;
    
    /// <remarks/>
    public WareHouse() {
        this.Url = "http://localhost:3150/WareHouse.asmx";
    }
    
    /// <remarks/>
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;
    
    /// <remarks/>
    public event ReturnItemCompletedEventHandler ReturnItemCompleted;
    
    /// <remarks/>
    public event UpdateMoneyUserCompletedEventHandler UpdateMoneyUserCompleted;
    
    /// <remarks/>
    public event BuyItemCompletedEventHandler BuyItemCompleted;
    
    /// <remarks/>
    public event GetMedalCompletedEventHandler GetMedalCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld() {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloWorldAsync() {
        this.HelloWorldAsync(null);
    }
    
    /// <remarks/>
    public void HelloWorldAsync(object userState) {
        if ((this.HelloWorldOperationCompleted == null)) {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
    }
    
    private void OnHelloWorldOperationCompleted(object arg) {
        if ((this.HelloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReturnItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string[] ReturnItem() {
        object[] results = this.Invoke("ReturnItem", new object[0]);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void ReturnItemAsync() {
        this.ReturnItemAsync(null);
    }
    
    /// <remarks/>
    public void ReturnItemAsync(object userState) {
        if ((this.ReturnItemOperationCompleted == null)) {
            this.ReturnItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReturnItemOperationCompleted);
        }
        this.InvokeAsync("ReturnItem", new object[0], this.ReturnItemOperationCompleted, userState);
    }
    
    private void OnReturnItemOperationCompleted(object arg) {
        if ((this.ReturnItemCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ReturnItemCompleted(this, new ReturnItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateMoneyUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int UpdateMoneyUser(int id, int money) {
        object[] results = this.Invoke("UpdateMoneyUser", new object[] {
                    id,
                    money});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateMoneyUserAsync(int id, int money) {
        this.UpdateMoneyUserAsync(id, money, null);
    }
    
    /// <remarks/>
    public void UpdateMoneyUserAsync(int id, int money, object userState) {
        if ((this.UpdateMoneyUserOperationCompleted == null)) {
            this.UpdateMoneyUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMoneyUserOperationCompleted);
        }
        this.InvokeAsync("UpdateMoneyUser", new object[] {
                    id,
                    money}, this.UpdateMoneyUserOperationCompleted, userState);
    }
    
    private void OnUpdateMoneyUserOperationCompleted(object arg) {
        if ((this.UpdateMoneyUserCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateMoneyUserCompleted(this, new UpdateMoneyUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuyItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int BuyItem(int id, int item) {
        object[] results = this.Invoke("BuyItem", new object[] {
                    id,
                    item});
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void BuyItemAsync(int id, int item) {
        this.BuyItemAsync(id, item, null);
    }
    
    /// <remarks/>
    public void BuyItemAsync(int id, int item, object userState) {
        if ((this.BuyItemOperationCompleted == null)) {
            this.BuyItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyItemOperationCompleted);
        }
        this.InvokeAsync("BuyItem", new object[] {
                    id,
                    item}, this.BuyItemOperationCompleted, userState);
    }
    
    private void OnBuyItemOperationCompleted(object arg) {
        if ((this.BuyItemCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.BuyItemCompleted(this, new BuyItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMedal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int[] GetMedal(int idpet) {
        object[] results = this.Invoke("GetMedal", new object[] {
                    idpet});
        return ((int[])(results[0]));
    }
    
    /// <remarks/>
    public void GetMedalAsync(int idpet) {
        this.GetMedalAsync(idpet, null);
    }
    
    /// <remarks/>
    public void GetMedalAsync(int idpet, object userState) {
        if ((this.GetMedalOperationCompleted == null)) {
            this.GetMedalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMedalOperationCompleted);
        }
        this.InvokeAsync("GetMedal", new object[] {
                    idpet}, this.GetMedalOperationCompleted, userState);
    }
    
    private void OnGetMedalOperationCompleted(object arg) {
        if ((this.GetMedalCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetMedalCompleted(this, new GetMedalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void ReturnItemCompletedEventHandler(object sender, ReturnItemCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ReturnItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ReturnItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void UpdateMoneyUserCompletedEventHandler(object sender, UpdateMoneyUserCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateMoneyUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateMoneyUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void BuyItemCompletedEventHandler(object sender, BuyItemCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BuyItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal BuyItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
public delegate void GetMedalCompletedEventHandler(object sender, GetMedalCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetMedalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetMedalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int[])(this.results[0]));
        }
    }
}
